const schemaTables = [
  { name: 'companies', fields: ['company_id', 'canonical_name_zh', 'canonical_name_en', 'industry_group', 'region_id'] },
  { name: 'company_aliases', fields: ['alias_id', 'company_id', 'alias_name', 'source_id', 'confidence'] },
  { name: 'sources', fields: ['source_id', 'source_name', 'source_type', 'access_method', 'volatility'] },
  { name: 'source_rows', fields: ['row_id', 'source_id', 'raw_payload', 'fetched_at', 'parse_status'] },
  { name: 'company_sources', fields: ['company_id', 'source_id', 'field_name', 'evidence_value', 'verified_at'] },
  { name: 'company_profiles', fields: ['company_id', 'capital', 'responsible_person', 'address', 'lat_lng', 'last_updated'] },
  { name: 'company_tags', fields: ['company_id', 'tag', 'tag_group', 'confidence', 'evidence_source'] },
  { name: 'update_logs', fields: ['run_id', 'source_id', 'started_at', 'changed_rows', 'review_note'] },
];

export const DEEPTECH_CONTENT = {
  en: {
    hero: {
      label: 'Ecosystem Intelligence Infrastructure',
      title: 'Global DeepTech Database',
      oneLiner: 'From fragmented deep-tech signals to a research-grade ecosystem intelligence database.',
      summary: 'I built a research-oriented data workflow that consolidates public and manually maintained company signals into traceable, normalized, dashboard-ready research assets for ITRI/ISTI analysis.',
      meta: ['ITRI/ISTI research work', 'Python / Pandas / Playwright / SQL', '230+ companies tracked', 'Entity resolution / source traceability', '2024-Present'],
      console: {
        sourcesTitle: 'Source signals',
        coreTitle: 'Research database',
        outputsTitle: 'Decision surfaces',
        sources: ['MOPS', '104', 'TSIA', 'SEMI', 'ASIP', 'Startup lists', 'News', 'Manual sheets'],
        core: ['companies', 'source_rows', 'aliases', 'profiles', 'tags', 'update_logs'],
        outputs: ['Power BI', 'HTML map', 'Excel package', 'Research brief'],
      },
    },
    problem: {
      title: 'The work started with unstable public signals.',
      lead: 'Deep-tech ecosystem research rarely starts with clean data. Names shift across sources, public pages use inconsistent formats, and spreadsheets quickly become hard to maintain.',
      quote: 'The challenge was not collecting more data. It was turning unstable public signals into a reusable research asset.',
      beforeLabel: 'Before',
      afterLabel: 'After',
      cards: [
        {
          title: 'Fragmented sources',
          before: 'Company registries, association lists, job pages, news, and manual sheets each told a partial story.',
          after: 'I treated every source as a registered signal with access method, freshness, trusted fields, and limits.',
        },
        {
          title: 'Unstable identity',
          before: 'Chinese names, English aliases, URLs, and renamed entities did not line up cleanly.',
          after: 'Alias mapping and canonical company profiles made records stable enough for comparison and review.',
        },
        {
          title: 'Research-ready output gap',
          before: 'Raw sheets could not reliably feed maps, dashboards, or briefing material.',
          after: 'The workflow produced analysis-ready views with source trails and quality controls attached.',
        },
      ],
    },
    pipeline: {
      title: 'Source-to-output architecture',
      lead: 'The pipeline collects raw public and manually maintained data, preserves source rows, normalizes company identity, enriches profiles, stores relational evidence, and exports analysis-ready views.',
      labels: { inputs: 'inputs', operations: 'operations', outputs: 'outputs' },
      stages: [
        {
          id: 'source',
          step: '00',
          title: 'Source Signals',
          subtitle: 'Public, semi-structured, and manual ecosystem data.',
          inputs: ['Public registries', 'MOPS disclosures', '104 job pages', 'TSIA / SEMI / ASIP', 'Startup lists', 'News search', 'Manual spreadsheets'],
          operations: ['source registry', 'fetch timestamp', 'access notes', 'trusted-field map'],
          outputs: ['source metadata', 'candidate rows'],
        },
        {
          id: 'staging',
          step: '01',
          title: 'Raw Staging',
          subtitle: 'Preserve the source before interpretation.',
          inputs: ['CSV / XLSX snapshots', 'HTML tables', 'manual rows'],
          operations: ['source_rows table', 'raw payload capture', 'timestamped fetch logs'],
          outputs: ['traceable raw rows', 'parse status'],
        },
        {
          id: 'cleaning',
          step: '02',
          title: 'Cleaning and Normalization',
          subtitle: 'Make unstable records comparable.',
          inputs: ['raw company names', 'addresses', 'sector labels', 'missing values'],
          operations: ['name normalization', 'missing flags', 'region parsing', 'category standardization'],
          outputs: ['clean staging table', 'review queue'],
        },
        {
          id: 'resolution',
          step: '03',
          title: 'Entity Resolution',
          subtitle: 'Map aliases into canonical companies.',
          inputs: ['company names', 'aliases', 'URLs', 'addresses'],
          operations: ['alias mapping', 'duplicate candidates', 'confidence scoring', 'source comparison'],
          outputs: ['canonical profile', 'company_aliases'],
        },
        {
          id: 'enrichment',
          step: '04',
          title: 'Profile Enrichment',
          subtitle: 'Add governance, hiring, location, and ecosystem fields.',
          inputs: ['registry fields', 'job pages', 'association records', 'news'],
          operations: ['field extraction', 'lat/lng mapping', 'technology tagging', 'freshness checks'],
          outputs: ['company_profiles', 'company_tags', 'location_index'],
        },
        {
          id: 'database',
          step: '05',
          title: 'Research Database',
          subtitle: 'A reusable intelligence layer.',
          inputs: ['clean rows', 'canonical entities', 'source evidence'],
          operations: ['relational indexing', 'source linkage', 'version snapshots'],
          outputs: ['companies', 'sources', 'source_rows', 'company_sources'],
        },
        {
          id: 'analysis',
          step: '06',
          title: 'Analysis Mart',
          subtitle: 'Shape the evidence for research questions.',
          inputs: ['filtered entities', 'quality summary', 'tag groups'],
          operations: ['ecosystem segmentation', 'value-chain view', 'geography distribution'],
          outputs: ['analysis views', 'dashboard tables'],
        },
        {
          id: 'outputs',
          step: '07',
          title: 'Dashboards and Research Outputs',
          subtitle: 'Make the database usable for analysis and communication.',
          inputs: ['analysis mart', 'map-ready fields', 'briefing tables'],
          operations: ['Power BI views', 'HTML map export', 'Excel package', 'research brief'],
          outputs: ['ecosystem map', 'dashboard-ready dataset', 'meeting material'],
        },
      ],
    },
    workbench: {
      title: 'Entity normalization workbench',
      lead: 'A concrete before-and-after view shows how messy records become stable company profiles without losing their source trail.',
      sampleNote: 'Sample display based on the project workflow. Sensitive company-level records are not exposed.',
      confidenceLabel: 'confidence score',
      aliasesLabel: 'Alias mapping',
      tabs: [
        {
          id: 'raw',
          label: 'Raw input',
          title: 'Raw input snapshot',
          fields: [
            ['公司名稱', '台積電 / TSMC / Taiwan Semiconductor Manufacturing Co.'],
            ['Source', 'association list / MOPS / 104 page / manual spreadsheet'],
            ['Region', 'Hsinchu / 新竹市 / Hsinchu Science Park'],
            ['Category', 'semiconductor / IC manufacturing / foundry'],
            ['Missing', 'capital, founder, coordinates, hiring count'],
          ],
        },
        {
          id: 'cleaned',
          label: 'Normalized',
          title: 'Normalized company profile',
          fields: [
            ['canonical_name_zh', '台灣積體電路製造股份有限公司'],
            ['canonical_name_en', 'Taiwan Semiconductor Manufacturing Co.'],
            ['aliases', '台積電, TSMC, Taiwan Semiconductor'],
            ['source_count', '4 source families'],
            ['industry_tags', 'semiconductor, foundry, advanced manufacturing'],
            ['last_verified_at', 'sample timestamp'],
          ],
        },
        {
          id: 'trail',
          label: 'Source trail',
          title: 'Evidence trail',
          fields: [
            ['association list', 'alias / sector hint / candidate'],
            ['MOPS', 'registration and governance reference'],
            ['104 page', 'hiring signal and operating location'],
            ['manual spreadsheet', 'research-maintained field override'],
          ],
        },
      ],
      aliases: ['台積電', 'TSMC', 'Taiwan Semiconductor', 'TSMC Hsinchu'],
      canonical: 'canonical company profile',
      confidence: '0.86',
    },
    schema: {
      title: 'Database model, not a spreadsheet archive',
      lead: 'Instead of treating each spreadsheet as a final artifact, I modeled the workflow as a reusable intelligence layer.',
      body: 'Raw rows stay traceable, canonical companies stay stable, and every enriched field can point back to its source evidence.',
      tables: schemaTables,
      relations: ['aliases map to companies', 'source rows preserve raw evidence', 'company_sources links fields to proof', 'profiles and tags power research views'],
    },
    quality: {
      title: 'Data quality and reliability board',
      lead: 'The QA layer is designed to make uncertainty visible. Weak evidence becomes a review state, not a silent database field.',
      note: 'Sample display based on project workflow. Only public-safe metrics are shown.',
      cards: [
        { label: 'Coverage', value: '230+', caption: 'companies tracked and enriched through the research workflow' },
        { label: 'Traceability', value: 'source-linked', caption: 'raw rows preserved with source metadata and review notes' },
        { label: 'Identity control', value: 'alias-aware', caption: 'canonical profiles keep Chinese and English names aligned' },
        { label: 'Freshness', value: 'versioned', caption: 'update snapshots and stale-source checks support refresh discipline' },
        { label: 'Conflict handling', value: 'review queue', caption: 'duplicates and conflicting values stay visible for manual review' },
        { label: 'Output readiness', value: 'dashboard-ready', caption: 'Power BI, HTML map, Excel, and research brief handoff' },
      ],
    },
    outputs: {
      title: 'What the database enabled',
      lead: 'The final outputs turned the database into working research material: searchable indexes, maps, dashboards, enriched packages, and stakeholder-ready briefs.',
      dictionaryTitle: 'field dictionary preview',
      artifacts: [
        { title: 'Startup / DeepTech Company Index', desc: 'Searchable table and company profile structure with aliases, tags, and review state.', type: 'index' },
        { title: 'Taiwan Semiconductor / DeepTech Map', desc: 'Region-based mapping supported by normalized city, park, latitude, and longitude fields.', type: 'map' },
        { title: 'Ecosystem Segmentation Dashboard', desc: 'Category distribution, region clusters, source coverage, and trend filters for analysis.', type: 'dashboard' },
        { title: 'Research Brief Materials', desc: 'Analysis-ready exports for internal research, meetings, and stakeholder communication.', type: 'brief' },
        { title: 'Enriched Dataset Package', desc: 'Clean CSV, XLSX, and SQL-ready tables with source metadata and update protocol.', type: 'package' },
      ],
      dictionary: [
        ['field', 'company_id'],
        ['type', 'stable key'],
        ['source', 'company_sources'],
        ['review', 'required before export'],
      ],
    },
    methods: {
      title: 'Technical method details',
      lead: 'The implementation combined acquisition, cleaning, database modeling, visualization handoff, and reliability controls.',
      groups: [
        { title: 'Acquisition', items: ['Playwright for dynamic pages', 'Structured requests for stable pages', 'Manual spreadsheet ingestion', 'Cache fallback for unstable fetches'] },
        { title: 'Cleaning', items: ['Pandas table normalization', 'Missing-value flags', 'Deduplication and alias mapping', 'Column and type standardization'] },
        { title: 'Database modeling', items: ['Canonical company table', 'Alias relation table', 'Source registry', 'Source-to-company join table', 'Version snapshots'] },
        { title: 'Visualization', items: ['Power BI dashboard outputs', 'HTML ecosystem map', 'Filterable company intelligence views', 'Analysis-ready export tables'] },
        { title: 'Reliability', items: ['Append-only update protocol', 'Source traceability', 'Manual review queue', 'Field-level confidence indicator'] },
      ],
    },
    impact: {
      title: 'Role-fit impact',
      lead: 'The case translates technical work into portfolio proof for product, research, frontend, and data platform roles.',
      cards: [
        { role: 'AI Product Designer', text: 'Turned ambiguous research needs into a structured intelligence workflow and interface-ready outputs.' },
        { role: 'UX Researcher', text: 'Organized messy ecosystem data into a traceable evidence base for trend analysis and stakeholder communication.' },
        { role: 'Front-End Product Engineer', text: 'Designed high-fidelity data-system UI modules, diagrams, responsive patterns, and inspectable state.' },
        { role: 'Technical PM / Data Platform', text: 'Mapped source complexity, quality controls, update protocols, and output requirements into an implementation-ready system.' },
      ],
      reflectionTitle: 'Next iteration',
      reflection: 'The next version would formalize automated data validation, introduce scheduled ingestion, add source-level confidence scoring, and expose a lightweight internal search interface for faster research workflows.',
    },
  },
  zh: {
    hero: {
      label: '產業生態情報資料基礎建設',
      title: '全球深科技資料庫',
      oneLiner: '將分散的深科技與半導體產業訊號，整理成可查證、可索引、可分析的研究級資料庫。',
      summary: '我建立一套研究導向的資料流程，將公開與人工維護的公司訊號整合成可追溯、可標準化、可接入儀表板的研究資產，支援 ITRI/ISTI 的產業分析。',
      meta: ['ITRI/ISTI 研究工作', 'Python / Pandas / Playwright / SQL', '230+ 家公司追蹤', '實體解析 / 來源追溯', '2024-Present'],
      console: {
        sourcesTitle: '來源訊號',
        coreTitle: '研究資料庫',
        outputsTitle: '決策輸出',
        sources: ['MOPS', '104', 'TSIA', 'SEMI', 'ASIP', '新創名單', '新聞', '人工表格'],
        core: ['companies', 'source_rows', 'aliases', 'profiles', 'tags', 'update_logs'],
        outputs: ['Power BI', 'HTML 地圖', 'Excel 套件', '研究 brief'],
      },
    },
    problem: {
      title: '這項工作從不穩定的公開訊號開始。',
      lead: '深科技生態研究通常不是從乾淨資料開始。公司名稱在不同來源中不一致，公開頁面格式不穩定，手動表格也很快變得難以維護。',
      quote: '真正的挑戰不是蒐集更多資料，而是把不穩定的公開訊號整理成可重複使用的研究資產。',
      beforeLabel: '原始狀態',
      afterLabel: '整理後',
      cards: [
        {
          title: '分散來源',
          before: '公司登記、協會名單、徵才頁、新聞與人工表格各自只提供部分線索。',
          after: '我把每個來源登錄為訊號，記錄接入方式、更新鮮度、可信欄位與限制。',
        },
        {
          title: '不穩定身份',
          before: '中文名稱、英文別名、網址與更名資訊無法自然對齊。',
          after: '透過別名映射與標準公司檔案，讓紀錄可以被比較、查詢與審核。',
        },
        {
          title: '研究輸出落差',
          before: '原始表格無法穩定支援地圖、儀表板或研究簡報。',
          after: '流程輸出可分析資料視圖，並且保留來源脈絡與品質控制。',
        },
      ],
    },
    pipeline: {
      title: '從來源到輸出的資料架構',
      lead: '整體流程蒐集公開與人工維護資料、保留原始來源列、標準化公司身份、補強公司檔案、儲存關聯式證據，最後輸出可供分析使用的資料視圖。',
      labels: { inputs: '輸入', operations: '處理', outputs: '輸出' },
      stages: [
        {
          id: 'source',
          step: '00',
          title: '來源訊號',
          subtitle: '公開、半結構化與人工維護的生態資料。',
          inputs: ['公開登記資料', 'MOPS 揭露', '104 徵才頁', 'TSIA / SEMI / ASIP', '新創名單', '新聞搜尋', '人工表格'],
          operations: ['來源登錄', '擷取時間戳', '接入備註', '可信欄位地圖'],
          outputs: ['來源 metadata', '候選資料列'],
        },
        {
          id: 'staging',
          step: '01',
          title: '原始暫存',
          subtitle: '先保留來源，再進行解讀。',
          inputs: ['CSV / XLSX 快照', 'HTML 表格', '人工維護列'],
          operations: ['source_rows table', 'raw payload 保存', '擷取紀錄'],
          outputs: ['可追溯原始列', '解析狀態'],
        },
        {
          id: 'cleaning',
          step: '02',
          title: '清理與標準化',
          subtitle: '讓不穩定資料可以被比較。',
          inputs: ['原始公司名', '地址', '產業標籤', '缺失值'],
          operations: ['名稱標準化', '缺失標記', '區域解析', '類別標準化'],
          outputs: ['乾淨暫存表', '審核佇列'],
        },
        {
          id: 'resolution',
          step: '03',
          title: '實體解析',
          subtitle: '將別名對應到標準公司實體。',
          inputs: ['公司名稱', '別名', '網址', '地址'],
          operations: ['別名映射', '重複候選', '可信度評分', '跨來源比對'],
          outputs: ['標準公司檔案', 'company_aliases'],
        },
        {
          id: 'enrichment',
          step: '04',
          title: '公司資料補強',
          subtitle: '補強治理、徵才、地理與生態欄位。',
          inputs: ['登記欄位', '徵才頁', '協會資料', '新聞'],
          operations: ['欄位擷取', 'lat/lng 映射', '技術標籤', '鮮度檢查'],
          outputs: ['company_profiles', 'company_tags', 'location_index'],
        },
        {
          id: 'database',
          step: '05',
          title: '研究資料庫',
          subtitle: '可重複使用的情報資料層。',
          inputs: ['清理後資料', '標準實體', '來源證據'],
          operations: ['關聯式索引', '來源鏈接', '版本快照'],
          outputs: ['companies', 'sources', 'source_rows', 'company_sources'],
        },
        {
          id: 'analysis',
          step: '06',
          title: '分析資料層',
          subtitle: '讓證據對應研究問題。',
          inputs: ['篩選實體', '品質摘要', '標籤群組'],
          operations: ['生態分群', '價值鏈視圖', '地理分布'],
          outputs: ['分析視圖', '儀表板資料表'],
        },
        {
          id: 'outputs',
          step: '07',
          title: '儀表板與研究輸出',
          subtitle: '讓資料庫支援分析與溝通。',
          inputs: ['分析資料層', '地圖欄位', '簡報資料表'],
          operations: ['Power BI 視圖', 'HTML 地圖匯出', 'Excel 套件', '研究 brief'],
          outputs: ['生態地圖', '儀表板資料集', '會議素材'],
        },
      ],
    },
    workbench: {
      title: '實體標準化工作台',
      lead: '具體的 before-and-after 視圖，呈現混亂紀錄如何轉成穩定公司檔案，同時不失去來源脈絡。',
      sampleNote: '此為根據專案流程製作的公開安全樣本，不揭露敏感公司級資料。',
      confidenceLabel: '可信度分數',
      aliasesLabel: '別名映射',
      tabs: [
        {
          id: 'raw',
          label: '原始資料',
          title: '原始輸入快照',
          fields: [
            ['公司名稱', '台積電 / TSMC / Taiwan Semiconductor Manufacturing Co.'],
            ['Source', 'association list / MOPS / 104 page / manual spreadsheet'],
            ['Region', 'Hsinchu / 新竹市 / Hsinchu Science Park'],
            ['Category', 'semiconductor / IC manufacturing / foundry'],
            ['Missing', 'capital, founder, coordinates, hiring count'],
          ],
        },
        {
          id: 'cleaned',
          label: '標準化',
          title: '標準公司檔案',
          fields: [
            ['canonical_name_zh', '台灣積體電路製造股份有限公司'],
            ['canonical_name_en', 'Taiwan Semiconductor Manufacturing Co.'],
            ['aliases', '台積電, TSMC, Taiwan Semiconductor'],
            ['source_count', '4 source families'],
            ['industry_tags', 'semiconductor, foundry, advanced manufacturing'],
            ['last_verified_at', 'sample timestamp'],
          ],
        },
        {
          id: 'trail',
          label: '來源軌跡',
          title: '證據軌跡',
          fields: [
            ['association list', 'alias / sector hint / candidate'],
            ['MOPS', 'registration and governance reference'],
            ['104 page', 'hiring signal and operating location'],
            ['manual spreadsheet', 'research-maintained field override'],
          ],
        },
      ],
      aliases: ['台積電', 'TSMC', 'Taiwan Semiconductor', 'TSMC Hsinchu'],
      canonical: '標準公司檔案',
      confidence: '0.86',
    },
    schema: {
      title: '資料庫模型，而不是試算表堆疊',
      lead: '我沒有把每份試算表當成最終產物，而是把流程設計成可重複使用的情報層。',
      body: '原始列保留可追溯性，標準公司實體保持穩定，每個補強欄位都能回到來源證據進行檢查。',
      tables: schemaTables,
      relations: ['別名對應到公司實體', 'source_rows 保留原始證據', 'company_sources 將欄位連回來源', 'profiles 與 tags 支援研究視圖'],
    },
    quality: {
      title: '資料品質與可靠性看板',
      lead: 'QA 層的目標是讓不確定性可見。弱證據會進入審核狀態，而不是默默成為資料庫欄位。',
      note: '此為根據專案流程製作的樣本展示，只呈現公開安全指標。',
      cards: [
        { label: '覆蓋範圍', value: '230+', caption: '透過研究流程追蹤與補強的公司紀錄' },
        { label: '來源追溯', value: 'source-linked', caption: '原始列保留來源 metadata 與審核備註' },
        { label: '身份控制', value: 'alias-aware', caption: '標準檔案對齊中文與英文公司名稱' },
        { label: '更新鮮度', value: 'versioned', caption: '版本快照與 stale-source 檢查支援更新紀律' },
        { label: '衝突處理', value: 'review queue', caption: '重複候選與衝突欄位保持可見，交給人工審核' },
        { label: '輸出準備度', value: 'dashboard-ready', caption: '支援 Power BI、HTML 地圖、Excel 與研究 brief 交付' },
      ],
    },
    outputs: {
      title: '資料庫實際支援的產出',
      lead: '最終產出把資料庫轉成可工作的研究素材，包括公司索引、地圖、儀表板、補強資料包與利害關係人簡報。',
      dictionaryTitle: '欄位字典預覽',
      artifacts: [
        { title: 'Startup / DeepTech Company Index', desc: '可搜尋公司表與 profile 結構，包含別名、標籤與審核狀態。', type: 'index' },
        { title: 'Taiwan Semiconductor / DeepTech Map', desc: '以標準化城市、園區、緯度與經度欄位支援區域地圖。', type: 'map' },
        { title: 'Ecosystem Segmentation Dashboard', desc: '呈現類別分布、區域群聚、來源覆蓋與趨勢篩選。', type: 'dashboard' },
        { title: 'Research Brief Materials', desc: '為內部研究、會議與利害關係人溝通準備的分析輸出。', type: 'brief' },
        { title: 'Enriched Dataset Package', desc: '整理為 CSV、XLSX 與 SQL-ready tables，附來源 metadata 與更新 protocol。', type: 'package' },
      ],
      dictionary: [
        ['field', 'company_id'],
        ['type', 'stable key'],
        ['source', 'company_sources'],
        ['review', 'required before export'],
      ],
    },
    methods: {
      title: '技術方法細節',
      lead: '整體實作結合資料擷取、清理、資料庫建模、視覺化交付與可靠性控制。',
      groups: [
        { title: 'Acquisition', items: ['Playwright 處理動態頁面', '穩定頁面使用結構化 request', '人工表格匯入', '不穩定擷取使用快取回退'] },
        { title: 'Cleaning', items: ['Pandas 表格標準化', '缺失值標記', '去重與別名映射', '欄位與型別標準化'] },
        { title: 'Database Modeling', items: ['標準公司表', '別名關聯表', '來源 registry', '來源與公司 join table', '版本快照'] },
        { title: 'Visualization', items: ['Power BI 儀表板輸出', 'HTML 生態地圖', '可篩選公司情報視圖', '可分析匯出表'] },
        { title: 'Reliability', items: ['附加式更新 protocol', '來源追溯', '人工審核佇列', '欄位層級可信度指標'] },
      ],
    },
    impact: {
      title: '對應職能價值',
      lead: '這個案例把技術工作轉譯為產品、研究、前端與資料平台職能都能理解的作品集證據。',
      cards: [
        { role: 'AI Product Designer', text: '將模糊研究需求轉成結構化情報流程與可接入介面的輸出。' },
        { role: 'UX Researcher', text: '把混亂產業資料整理成可追溯的證據基礎，用於趨勢分析與利害關係人溝通。' },
        { role: 'Front-End Product Engineer', text: '設計高擬真資料系統 UI 模組、架構圖、響應式互動與可檢視狀態。' },
        { role: 'Technical PM / Data Platform', text: '將來源複雜度、品質控制、更新 protocol 與輸出需求整理成可實作系統。' },
      ],
      reflectionTitle: '下一版方向',
      reflection: '下一版可以進一步加入自動化資料驗證、排程更新、來源可信度評分，並建立輕量級內部搜尋介面，讓研究流程更快完成查詢、比對與輸出。',
    },
  },
};

export function getDeepTechContent(lang) {
  return DEEPTECH_CONTENT[lang === 'zh' ? 'zh' : 'en'];
}
