import React from 'react';
import { useLang } from '../app/providers/LanguageProvider.jsx';
import { useReveal } from '../hooks/useReveal.js';
import { scrollTo } from '../utils/scrollTo.js';
import { PROJECTS } from '../data/projects.js';
import ProjectCard from '../components/home/ProjectCard.jsx';
import SkillsSection from '../components/home/SkillsSection.jsx';
import AwardsSection from '../components/home/AwardsSection.jsx';

export default function HomePage({ navigate }) {
    const { t, lang } = useLang();
    useReveal([lang]);
    const timeline = [
        { meta: t('ch0Meta'), head: t('ch0Head'), body: t('ch0Body'), type: 'research',
          chips: ['NCCU / M.S. Psych', 'TMBIC', 'fMRI / EEG', 'OHBM 2025', 'TSCN 2025', 'I-9-9 Berlin'] },
        { meta: t('ch1Meta'), head: t('ch1Head'), body: t('ch1Body'), type: 'research',
          chips: ['MoHW Mental Health', 'Children & Family Welfare', 'Mennonite Hospital', 'UX Research', 'Data Analysis'] },
        { meta: t('ch2Meta'), head: t('ch2Head'), body: t('ch2Body'), type: 'product',
          chips: ['LLM', 'UX Research', 'Risk Detection', 'FastAPI', 'Silver Medal 2025'] },
        { meta: t('ch3Meta'), head: t('ch3Head'), body: t('ch3Body'), type: 'industry',
          chips: ['ETL Pipelines', 'Market Analysis', 'Web Crawling', 'Full-Stack Dev', 'Star Program 2025'] },
        { meta: t('ch4Meta'), head: t('ch4Head'), body: t('ch4Body'), type: 'future',
          chips: ['AI Products', 'Research × PM', 'Open to Opportunities'] },
    ];
    return React.createElement('div', { className: 'page-enter' },
        React.createElement('section', { className: 'hero', id: 'top' },
            React.createElement('div', { className: 'hero-left' },
                React.createElement('div', { className: 'hero-status' },
                    React.createElement('span', { className: 'status-item status-active' },
                        React.createElement('span', { className: 'status-dot' }), t('heroStatusActive')),
                    React.createElement('span', { className: 'status-sep' }, '·'),
                    React.createElement('span', { className: 'status-item status-open' },
                        React.createElement('span', { className: 'status-dot amber' }), t('heroStatusOpen'))),
                React.createElement('p', { className: 'hero-eyebrow' }, t('heroEyebrow')),
                React.createElement('h1', { className: 'hero-title' },
                    lang === 'en'
                        ? React.createElement(React.Fragment, null,
                            'I turn frontier-tech', React.createElement('br', null),
                            'signals into', React.createElement('br', null),
                            React.createElement('em', null, t('heroTitleEm')), React.createElement('br', null),
                            t('heroTitle2'))
                        : React.createElement(React.Fragment, null,
                            t('heroTitle1'), React.createElement('br', null),
                            React.createElement('em', null, t('heroTitleEm')), React.createElement('br', null),
                            t('heroTitle2'))),
                React.createElement('p', { className: 'hero-sub' }, t('heroSub')),
                React.createElement('div', { className: 'hero-actions' },
                    React.createElement('button', { className: 'btn-primary', onClick: () => scrollTo('work', 0) }, t('heroCta1')),
                    React.createElement('button', { className: 'btn-ghost', onClick: () => scrollTo('story', 0) }, t('heroCta2'))),
                React.createElement('div', { className: 'hero-stats' },
                    React.createElement('div', { className: 'hero-stat' },
                        React.createElement('div', { className: 'stat-num' }, '3+'),
                        React.createElement('div', { className: 'stat-label' }, t('statYears'))),
                    React.createElement('div', { className: 'hero-stat' },
                        React.createElement('div', { className: 'stat-num' }, '7'),
                        React.createElement('div', { className: 'stat-label' }, t('statProjects'))),
                    React.createElement('div', { className: 'hero-stat' },
                        React.createElement('div', { className: 'stat-num', style: { color: 'var(--amber)' } }, '4'),
                        React.createElement('div', { className: 'stat-label' }, t('statAwards'))),
                    React.createElement('div', { className: 'hero-stat' },
                        React.createElement('div', { className: 'stat-num' }, '2'),
                        React.createElement('div', { className: 'stat-label' }, t('statPub'))))),
            React.createElement('div', { className: 'hero-right' },
                React.createElement('div', { className: 'hero-img-wrap' },
                    React.createElement('div', { className: 'scan-line' }),
                    React.createElement('img', { src: 'assets/cv_visual.webp', alt: 'Guan-Ting Ye — Deep Tech Translator', width: '780', height: '1020', decoding: 'async', fetchPriority: 'high' }),
                    React.createElement('div', { className: 'hero-img-glow' }),
                    React.createElement('div', { className: 'hero-coords' }, '25.04°N · 121.56°E'),
                    React.createElement('div', { className: 'data-tag' }, t('tagActive')),
                    React.createElement('div', { className: 'data-tag-2' }, t('tagAward'))))),
        React.createElement('section', { className: 'story', id: 'story' },
            React.createElement('div', { className: 'container' },
                React.createElement('div', { className: 'section-label reveal' }, t('storyLabel')),
                React.createElement('h2', { className: 'section-title reveal reveal-delay-1' },
                    t('storyTitle1'), React.createElement('br', null),
                    React.createElement('em', null, t('storyTitleEm')), t('storyTitle2')),
                React.createElement('div', { className: 'timeline' },
                    timeline.map((item, i) => React.createElement('div', { className: 'timeline-item', key: i, 'data-type': item.type },
                        React.createElement('div', { className: 'timeline-dot' }),
                        React.createElement('div', { className: 'timeline-meta' }, item.meta),
                        React.createElement('h3', { className: 'timeline-head' }, item.head),
                        React.createElement('p', { className: 'timeline-body' }, item.body),
                        React.createElement('div', { className: 'chips' }, item.chips.map(c => React.createElement('span', { className: 'chip', key: c }, c)))))))),
        React.createElement('section', { className: 'work', id: 'work' },
            React.createElement('div', { className: 'container' },
                React.createElement('div', { className: 'section-label reveal' }, t('workLabel')),
                React.createElement('h2', { className: 'section-title reveal reveal-delay-1' },
                    t('workTitle1'), ' ', React.createElement('em', null, t('workTitleEm')), t('workTitle2')),
                React.createElement('div', { className: 'work-grid' },
                    PROJECTS.map((p, i) => React.createElement(ProjectCard, { key: p.slug, project: p, index: i, navigate, lang }))))),
        React.createElement(SkillsSection, null),
        React.createElement(AwardsSection, null),
        React.createElement('section', { className: 'contact-section', id: 'contact' },
            React.createElement('div', { className: 'contact-ghost', 'aria-hidden': 'true' }, 'SIGNAL'),
            React.createElement('div', { className: 'container' },
                React.createElement('div', { className: 'section-label reveal' }, t('contactLabel')),
                React.createElement('div', { className: 'contact-grid' },
                    React.createElement('div', null,
                        React.createElement('h2', { className: 'contact-title reveal' },
                            t('contactTitle1'), ' ', React.createElement('em', null, t('contactTitleEm')), t('contactTitle2')),
                        React.createElement('p', { className: 'contact-note reveal reveal-delay-1' }, t('contactNote'))),
                    React.createElement('div', { className: 'contact-links reveal reveal-delay-2' },
                        React.createElement('a', { href: 'mailto:1126guanting@gmail.com', className: 'contact-link' },
                            React.createElement('div', null,
                                React.createElement('div', { className: 'contact-link-label' }, t('contactEmail')),
                                React.createElement('div', { className: 'contact-link-val' }, '1126guanting@gmail.com')),
                            React.createElement('span', { className: 'contact-link-arrow' }, '→')),
                        React.createElement('a', { href: 'tel:+886927012867', className: 'contact-link' },
                            React.createElement('div', null,
                                React.createElement('div', { className: 'contact-link-label' }, t('contactPhone')),
                                React.createElement('div', { className: 'contact-link-val' }, '+886 927 012 867')),
                            React.createElement('span', { className: 'contact-link-arrow' }, '→')),
                        React.createElement('div', { className: 'contact-link', style: { cursor: 'default' } },
                            React.createElement('div', null,
                                React.createElement('div', { className: 'contact-link-label' }, t('contactLang')),
                                React.createElement('div', { className: 'contact-link-val' }, 'Mandarin (Native) · English (Professional)')),
                            React.createElement('span', { className: 'contact-link-arrow', style: { color: 'var(--amber)' } }, '✦')))))));
}
